### ISSUE TITLE
Timeline viewer is broken for viewing the traces using the drive urls

### ISSUE THREAD

**Issue by aupadhyay-coursera** [ChromeDevTools/timeline-viewer#106]
The Timeline Viewer was functioning correctly until yesterday. However, following the merge of [this pull request](https://github.com/ChromeDevTools/timeline-viewer/pull/105), it's no longer loading timeline traces appropriately. This issue affects not just our specific use case, where we utilize Amazon Cloudfront to deliver the tracer.json file, but it is also evident when trying to load traces from the provided example link. We request you to investigate this issue promptly.

For instance- 
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/s1n8m8n5oddgoxx/timeline-docs.json?dl=0 or 
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json

**Comment by paulirish** [comment]
While I sort this out, you can use this:

https://chrome-devtools-frontend.appspot.com/serve_rev/@70f00f477937b61ba1876a1fdbf9f2e914f24fe3/worker_app.html?loadTimelineFromURL=https%253A%252F%252Ffirebasestorage.googleapis.com%252Fv0%252Fb%252Ftrace-uploading-maybe.appspot.com%252Fo%252Ftraces%25252Fo2XnQMHmWH%253Falt%253Dmedia%2526token%253Dde07bfd8-06b6-44dd-bb41-05ecbd06e79b

i believe the param value is encoded TWICE.

**Comment by aupadhyay-coursera** [comment]
Thanks a lot @paulirish for the workaround.

**Comment by denar90** [comment]
wow, happy to see folks are still using it :)

**Comment by paulirish** [comment]
> For instance- [chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/s1n8m8n5oddgoxx/timeline-docs.json?dl=0](https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/s1n8m8n5oddgoxx/timeline-docs.json?dl=0) or [chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json](https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json)


Sadly these two links broke for unrelated reasons. The assets were 404. I stopped paying for dropbox and i deleted a bunch of old gists. Didn't realize either would break the demo URLs over here. whoops!

here's a single-trace view link with a gist trace that doesnt 404. https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.github.com/paulirish/5b5d6bdcfde557ff3eec4571dc6a0485/raw/07bc7905441e45e1e1dc751cf09c3d640ab46fc0/hello-opp.trace.json

That said, I also made changes that affected trace loading and I think that also broke users. (And I messed up service worker removal). Going to resolve these latter two issues now…

**Comment by paulirish** [comment]
My own repro of 106:

- load in my regular non-incognito window https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.github.com/paulirish/5b5d6bdcfde557ff3eec4571dc6a0485/raw/07bc7905441e45e1e1dc751cf09c3d640ab46fc0/hello-opp.trace.json
- notice nothing happens


in my case. the old service worker was around. That led to a mismatch of old and new index.html and JS files, which generally just broke things.


If you load that url in incognito its fine,, because it wouldnt use the old cached pre-#105 SW.

**Comment by paulirish** [comment]
@aupadhyay-coursera thanks again for the prompt bug report.

This should be all fine now.
