### ISSUE TITLE
Drag&drop feature

### ISSUE THREAD

**Issue by denar90** [ChromeDevTools/timeline-viewer#11]
Add possibility to drag&drop file. Since TV (😭) has authorized permissions to gdrive, we can simplify users life giving them possibility to drag&drop file, then we upload it on gdrive and show timeline stuff.
wdyt?

p.s. as usual I can be in charge of that :)

**Comment by paulirish** [comment]
ya sg. drag and drop already works for viewing (i do this for comparisons pretty often)

but yeah if someone drag and drops a file, we could add a button that allows them to upload to gdrive.

sgtm

**Comment by denar90** [comment]
nice, I'll take a look after offline stuff

**Comment by paulirish** [comment]
fixed by #13
