### ISSUE TITLE
split view v2

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/timeline-viewer#4]
ideas from @samccone:

> basically
> allow snapping to a performance.mark
> to align 
> and always match the duration of the longest profile
> then if you lock zooming
> it will just work
> which is chill

**Comment by samccone** [comment]
vchill

**Comment by paulirish** [comment]
Made a comparison of FF debugger.html and Chrome DevTools opening (to debug node.js):

Here's snapping to navstart and aligning the timescale

![image](https://cloud.githubusercontent.com/assets/39191/18528245/092f2b08-7a7d-11e6-9db1-073e682cbb9f.png)

(manually, obv.)
but yes i would adore if this alignment and normalization was handled automatically. good god.

**Comment by paulirish** [comment]
was talking with @denar90 about this `synchronizedRange` selection UX on IM...

goal #1: make sure our `synchronizedRange` is revealign the same duration of time in both traces. So whenever a selection is made, the other one should be adjusted to show the same time duration in its selection window.

goal #2: align the startTime of the `synchronizedRange` windows. 

* as a first pass we could always start with the very beginning.  
* slightly improved might be: you have to drag a selection in both windows. Whereever that selection starts is the startTime of the `synchronizedRange` for that trace

thats my best at the moment. open to alternatives.

**Comment by denar90** [comment]
can we close this one, since https://github.com/ChromeDevTools/timeline-viewer/pull/17 and https://github.com/ChromeDevTools/timeline-viewer/pull/19 are merged?

**Comment by paulirish** [comment]
yup!

tho i found some bugs recently. ill file as new tickets. :)
