### ISSUE TITLE
the dropbox link on the homepage fails now

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/timeline-viewer#51]

**Comment by denar90** [comment]
Looks like smth wrong on our side. [Demo](https://denar90.github.io/dev-tools-element/demo/) for DevTools element works good with dropbox...

**Comment by paulirish** [comment]
Oh really! Same URL? Interesting..

**Comment by denar90** [comment]
Interesting thing, using normal reload (cmd + r) for https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/s1n8m8n5oddgoxx/timeline-docs.json?dl=0 it won't work, but using hard reload (cmd + shift + r) it works... Can it be some chrome bug?

**Comment by paulirish** [comment]
can't repro anymore.
