### ISSUE TITLE
Timeline Viewer Breaks on Chrome 80

### ISSUE THREAD

**Issue by seanenright** [ChromeDevTools/timeline-viewer#64]
**Issue**: 
With the chrome 80 release the timeline viewer no longer works.  

**things i've tried to fix**
I've attempted to debug and fix locally but haven't had any luck (yet).  The version of shelljs and dev_tools_app.js are outdated and use native methods that were dropped with the release of v80.

So far I've attempted updating the hash on line 74 and 75 in  [docs/index.html here
](https://github.com/ChromeDevTools/timeline-viewer/blob/42b07164027664c0a738bdb179e5fd31300ad352/docs/index.html#L75).  and the createSetting methods in[ docs/dev_tools.js
](https://github.com/ChromeDevTools/timeline-viewer/blob/42b07164027664c0a738bdb179e5fd31300ad352/docs/dev_tools.js#L59) but haven't had any success yet. 

I'm happy to keep hacking on this, but would <3 some help or direction.  

***Relevant logs from the console***:
`
shell.js:3123 Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (shell.js:3123)
    at shell.js:3135
    at shell.js:3137
devtools_app.js:2 Uncaught ReferenceError: SDK is not defined
    at devtools_app.js:2
treeoutlineTriangles_2x.png:1 Failed to load resource: the server responded with a status of 404 ()
?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json:1 A cookie associated with a cross-site resource at https://accounts.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json:1 A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
?loadTimelineFromURL=https://gist.github.com/paulirish/f83d30384954937dc3a1fae970a4ae52/raw/b25b27741c652d3091a316dfd8b58bf72f14aa74/twitch.json:1 A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
dev_tools.js:59 Uncaught TypeError: Cannot read property 'createSetting' of undefined
    at dev_tools.js:59
`

**Comment by seanenright** [comment]
@paulirish the viewer is not compatible with chrome 80.  Is there plans to update?

**Comment by paulirish** [comment]
thanks for reporting @seanenright 

i fixed it ;)

**Comment by paulirish** [comment]
and thanks for trying to fix it yourself. brave of you!

unfortunately the way this app is put together is pretty unorthodox so it was going to be a pretty rough learning curve. :)

cheers man. happy v day
