### ISSUE TITLE
Make it works offline

### ISSUE THREAD

**Issue by denar90** [ChromeDevTools/timeline-viewer#7]
It will be incredibly useful feature.
Load trace -> go offline -> refresh page -> still have data

---

 Since `timeline-viewer` site hosted with github (uses https) we can use service workers.

Thoughts?

P.S. I'd like to give it a shot 😃

**Comment by paulirish** [comment]
Yup! Definitely possible to make this work via service-workers.

Thumbs up!

**Comment by denar90** [comment]
I'll try to give it a shot, just need to extend 24 hours in a day 😄
