### ISSUE TITLE
Missing information opening lighthouse traces

### ISSUE THREAD

**Issue by dvelasquez** [ChromeDevTools/timeline-viewer#80]
Hey people, thanks very much for this awesome tool.

A little context: I'm working with lighthouse programmatically, and every time I run lighthouse I'm storing the traces and devtoolslog information. My idea is to be able to use this data to debug problems.

The issue I'm having is whenever I use the timeline-viewer, some information get lost or shows very different information than when I open the same trace in devtools.

For example: This is how a trace with the timeline-viewer looks like
![image](https://user-images.githubusercontent.com/4724505/99530246-5a83e980-29a1-11eb-9caa-bd332155dd50.png)

And this how it looks like in the chrome devtools
![image](https://user-images.githubusercontent.com/4724505/99530302-6b345f80-29a1-11eb-9332-f15c2727cf7b.png)

This is a gist with the trace: https://gist.githubusercontent.com/dvelasquez/0dc154ac0094f9f3b93ae92272a623da/raw/95a654573022deb81aca463b2fcd01b16f6c36be/trace-lighthouse.json

**Comment by paulirish** [comment]
There's an experiment called "Timeline: show all events"

![image](https://user-images.githubusercontent.com/39191/114588277-5a7bd300-9c3b-11eb-8ecd-105de25f95d8.png)

In timeline-viewer I force that experiment on (plus two others). 

https://github.com/ChromeDevTools/timeline-viewer/blob/f7afb198e35ba814bb94061eb01853f59c098bfa/docs/dev_tools.js#L23-L25

So you're just seeing additional info here that usually isn't shown.
