### ISSUE TITLE
[Question] Can this be used in the components world?

### ISSUE THREAD

**Issue by 40x** [ChromeDevTools/timeline-viewer#85]
Has there been any attempt in converting this tool into a component which can be installed and embedded into an existing web application (built with React/Angular/Vue etc)? Also, is this being actively maintained/developed?

**Comment by paulirish** [comment]
check out https://github.com/denar90/dev-tools-element
however it was made from an old version of the devtools, but there's a decent chance it still works.


timeline-viewer is.... lazily maintained. I usually fix breakages, but don't give it much more attention than that. (sadly)


i haven't updated in a while and the chrome devtools frontend has changed quite a bit. it'd be interesting to give it a go, but i won't be trying anytime soon.  
if you wanted a standalone component that can vizualize traces, i'd honestly try out pulling in https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/timeline/TimelinePanel.ts directly. it won't be easy, but ... probably possible.
